FROM python:3.7-slim-stretch
ADD requirements.txt /
RUN pip install -r /requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
ADD . /app
WORKDIR /app
EXPOSE 8081
CMD [ "python" , "./server/server.py"]